spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false
  h2:
    console:
      enabled: true

server:
  port: 8081 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: VFVsSlEyUlJTVUpCUkVGT1FtZHJjV2hyYVVjNWR6QkNRVkZGUmtGQlUwTkJiRGgzWjJkS1lrRm5SVUZCYjBkQ1FVbFlObUZzT0RZMFpHVmlXVGRUYW1WUldrVXpPSEJ6Um5KRmFreE5lRmhJVlhnM2F6SkdZMU4wWkd0dk1uZ3JUVkl5VHpCa1VFbDFkRzluYkVwcWMwNDJNblJKWmxVdlpGaERaSFIyT1hkSVF6TlFlbWhqTDFOUU0yMWhRMFpyU1ZwVlZGbG1Ra0ZPZDFKdmIwNHJSSFJwWm1OSGQzTkdORXN2ZVZNNVlrWlVOQzltZG1sR2VUZzVSbTVpZDJSellrRmxNRGc0VTJ3MWFVWnZWMjFQUkRKRFNEbDZNaTk0VlZORWJFRm5UVUpCUVVWRFoxbEJMMWxyY0VONFZuVnNTV3B0V1dONVNrWnBaalJMUTFCeWRsVk5TRmcxYm5KUkwxVkhjbVJRZEdaVVdtaFlUWEJvVURoSmNIRldTRTgxTUVkSlkzVjBlRmxwVTJ0bmJYRlpXRFJxVmpaUldFeEVXbUZYVFM5NVpWVnNjbXgyWkhkbVF6QmpWelF2ZUhSNVVXRlpTM0V4WXpsQ1JqWXhZMDQ1ZGtWTU1qVjVWa05DTXpFMk9EWm9WamhDYUU1eFZ6VnVkSFJ2YUcxMVNqZFFlR3hUV1RObFdqVlZNRkJvZDI4MlRsbFJTa0pCVGxGSE1YSlZOVFJIUjFoNWQyaG9iRnBTTUM4M2VtSkxRVWh4UzJablRFWmtRMUpsWmpod2NVNWpVa0pJVVRCVFdqRkVNVzFEYzJNM1pIcGhkRVZwVkROdFJYWjZObXhLZFhGaFlVNUJjSEpRUWtaNllqQkRVVkZEYUhjM2VVUlBhMWwzSzA5VFowVkdMMGxuZVRVelVGcFFRM0prVDNwM01FVmtjRFpvU20wMldIRjViVTF3VTBGcVlsQmhlRzh3UkhKcWJrYzJaR2xVVG5jcmVTOUdWMnRGVUhSMFMzWm1ZakkzYWpZMVNrRnJRbTU1TmpGRFlrMUliWEJPZFRGRU5tbGtWVFpXTm1VNFRXSktUbkJGTTNCQ1oxZFZaR2t6WVRoV1JXWlRaazl3VjNKRmJrZGFVUzlOYlVwTE9YWkZRaTlrSzJ4c2VGQnZTazV4VTJWVlpVVktPRWxZTHpGQmEwRnVSRWRVV2tkS2QxRXZhMUJUUkRaSVVHVlVjMmxPV1RoU2F6TjRha1JIVFZCcldWVnBTRFY0ZUdwUFJtRXJZbE5LYkRreWFXWTBSak54UXpsaVpqazRXRU56ZFVKVVJWRm5WWFpYVVhaNk1uQndVV3hvUVd0Q1VqUmhNM2RVV1d4a1JtVnhVMnAwYlRSTWJqbElSazFTUW5kaWFGVndWVWxSVXpoSFpXMU9WbGN4WTBSak5rdG9OMjh2V2pkek5raFlSbHAzTUV0aFNYRktPREZaWTFWVlVHczFhM1JWZEZoV2JHdGpOZz09
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
